version: "3.9"

services:
  backend-app:
    build: ./backend
    container_name: backend-app
    command: python app.py
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - app-network
    restart: always

  backend-server:
    build: ./backend
    container_name: backend-server
    command: python server.py
    env_file: .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - app-network
    restart: always

  backend-app1:
    build: ./backend
    container_name: backend-app1
    command: python app1.py
    env_file: .env
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./Frontend
    container_name: frontend-app
    ports:
      - "80:80"   # frontend runs on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
